### ISSUE TITLE
CUDA gpu cannot be initialized

### ISSUE THREAD

**Issue by lambwheit** [CryptoGraphics/VerthashMiner#11]
Hi,
I am testing the miner on a laptop with GPU0 (Nvidia geforce 2070 super) and GPU1 (intel uhd graphics), i have followed everything on this site https://vertcoin.miningpoolhub.com/ but i keep getting failed to initialise cuda, error code 35, which prevents the nvidia gpu from mining. i have tried turning off nvidia optimus so the laptop just runs on the dedicated gpu but it still fails to initialize cuda. 
it would be great if u can help, thanks in advanced.

**Comment by lambwheit** [comment]
temp work around found, run with arg --no-restrict-cuda which allows the nvidia gpu to opencl mode

**Comment by CryptoGraphics** [comment]
Hello.
To get CUDA working, make sure you have the latest NVIDIA driver installed (460.89 and up).
NVIDIA OpenCL mode achieves the same performance. The only drawback is 1 of your CPU cores will have 100% usage.
