### ISSUE TITLE
Would like to get this miner added to the PiMP OS miner line-up, but...

### ISSUE THREAD

**Issue by DocDrydenn** [CryptoGraphics/VerthashMiner#13]
Hello, 

I'm DocDrydenn, one of the developers for [PiMP OS](https://getpimp.org) and we've had some requests from our users to support your miner in our OS. I would really like to be able to add your miner to our line-up of supported miners, however, we can't add it without a working API for stats monitoring.

If you'd like to discuss more, please hit me up directly on the [PiMP OS Discord Server](https://discord.gg/grCbFsA) or here on GitHub.

Thanks for your time.
-Doc

**Comment by CryptoGraphics** [comment]
Hello.
I'll look into this feature after 0.7.0 release, which will introduce GPU monitoring and other stuff.
