### ISSUE TITLE
Configuration isn't working on Win 10

### ISSUE THREAD

**Issue by Ezylryb77** [CryptoGraphics/VerthashMiner#14]
Hello there,
I was trying to set the Verthashminer up, but it doesn't seem to work:
I generate the GenerateConfig.bat with "./VerthashMiner -g your_config_file.conf" in the correct folder, but on activation no config file is generated.

Any Idea?

**Comment by CryptoGraphics** [comment]
There is a typo in the documentation.
.bat file content must be:
`VerthashMiner -g your_config_file.conf`
instead of:
`./VerthashMiner -g your_config_file.conf`
