### ISSUE TITLE
Intel graphics card instead of my nvidia GTX 1050 ti

### ISSUE THREAD

**Issue by Lokkomotive** [CryptoGraphics/VerthashMiner#15]
Hello there, i have a problem, when i launch Vertcoin one click miner, it uses my integrated intel graphics card and not my real nvidia graphics card ( GTX 1050 TI), how can i fix it? Thanks in advance for the answer :)

**Comment by aakashkardam** [comment]
Try This :
Disable the intel graphics from device manager and then try to run the OCM. Make sure the driver for the GPU is updated to the latest version. You can enable the intel graphics while the OCM is running.

**Comment by CryptoGraphics** [comment]
VerthashMiner uses all available devices by default.
Use manual GPU selection.
