### ISSUE TITLE
Found 0 OpenCL devices

### ISSUE THREAD

**Issue by IggyJ** [CryptoGraphics/VerthashMiner#18]
Hi, when i start up the miner I get 0 OpenCL devices (although i get 1 CUDA device). I don't know if the issue is related, but my Hashrate is unrealistically high, whilst on the mining website it is reporting a hashrate of 0. There is already an issue opened about this, therefore I'm using this thread to address the first issue.

My specs are:
- GPU: Nvidia GTX 760 (2GB)
- CPU: Intel i7-3770
- RAM: 16 GB
- OS: Arch Linux x86_64
- Kernel: 5.10.13
- Nvidia Driver: 460.39
- CUDA: 11.2
- VerthashMiner: 0.6.2

Thanks.

**Comment by CryptoGraphics** [comment]
If the miner has been compiled with CUDA enabled, then all NVIDIA devices, which are supported by CUDA will be automatically ignored by the OpenCL backend, unless `--no-restrict-cuda` command line parameter is used.
