### ISSUE TITLE
Device Not Responding.  error code: 702.  Terminaning worker.

### ISSUE THREAD

**Issue by talllogic** [CryptoGraphics/VerthashMiner#21]
Trying to run Verthashminer 0.6.2 on a GT 710.  Running Windows 10.  CUDA v11.2, up to date drivers.
Tried adjusting work size down to 32000. (Also, default and 64000)

'ERROR cu_device(0):Device not responding.  error code: 702.  Terminaning worker...'

Also, "Terminaning"?

Cheers,
Matt

**Comment by volksplane** [comment]
Matt,
Had same problem on a GT 730.
Setting the worksize to 16384 got it up and running.
Good luck!

**Comment by CryptoGraphics** [comment]
Resolved with adaptive work size in v0.7.0.
