### ISSUE TITLE
download blocked by Chrome and Explorer

### ISSUE THREAD

**Issue by DukeNukem-dev** [CryptoGraphics/VerthashMiner#23]
Tried to download the latest release, both Chrome and Explorer block the download as dangerous. What gives?

**Explorer:**

![image](https://user-images.githubusercontent.com/54203477/107905007-8ebb7600-6fa1-11eb-92c9-03c33e5cb166.png)

**Chrome:**
![image](https://user-images.githubusercontent.com/54203477/107905061-b9a5ca00-6fa1-11eb-802b-4889c90408a7.png)

**Comment by CryptoGraphics** [comment]
Unfortunately, they "hate" mining software. You can either "Accept the risk" or compile miner from the source code.
