### ISSUE TITLE
Miner starts hashing on ONBOARD video card

### ISSUE THREAD

**Issue by swipester** [CryptoGraphics/VerthashMiner#24]
I noticed it will start to hash on onboard video card as well as video cards on risers. Is there any way to disable this I do not want to burn out my onboard video card.

**Comment by CryptoGraphics** [comment]
You can select devices manually. For example devices: 1,2,5
AMD:
`--cl-devices 1,2,5`
NVIDIA:
`--cu-devices 1,2,5`

Same goes for the configuration file. (Readme: **OpenCL device management** part can be applied to CUDA too).
