### ISSUE TITLE
Stratum Protocol - Any reason to rebroadcast jobs?

### ISSUE THREAD

**Issue by steveocrypto** [CryptoGraphics/VerthashMiner#25]
Some miners will consider the pool dead/offline if it doesn't receive any new jobs for around a minute.  Is there any reason to rebroadcast jobs with version 0.7.0 given that how long it takes go through a nonce range?

**Comment by CryptoGraphics** [comment]
Hello.
Currently, there is a hard-coded time-out limit: 2 minutes.

**Comment by steveocrypto** [comment]
> Hello.
> Currently, there is a hard-coded time-out limit: 2 minutes.

Thanks!
