### ISSUE TITLE
cl_device(*):Failed to copy Verthash data to the GPU memory

### ISSUE THREAD

**Issue by SveguS80** [CryptoGraphics/VerthashMiner#26]
I am running 6 RX570 4GB cards on an ASUS B250 EXPERT miningboard with 4GB of RAM. I can get all cards to work individually. When I try any combination of 4 cards they work together well. As soon as I add a 5th card to the configuration one of the cards will show up with the following error message.

cl_device(****device number, seems random each time which device it is *****):Failed to copy Verthash data to the GPU memory

if I add all 6 cards, two will show up with the same error message.

I would love to get this to work with all 6 cards. I am sure I have omitted vital information here. Please let me know if I need to share more about my setup to be able to figure this out.

Much apprecation for the effort that goes into all this.

Regards,

Sven

**Comment by aim67** [comment]
hi. generate a date file for all video cards or generate a new date file every time you add a video card

**Comment by SveguS80** [comment]
Thanks for the reply, may I ask for some clarification here. Do you mean that I should generate a new .dat file after installing and setting up all cards on the rig? or do you mean that I need a seperate .dat file for each individual card?

Just to confirm my findings i started from the beginning. With 4 cards and after regenerating the .dat file it just works straight away. With 5 cards after regenerating the .dat file, it stops working directly with the same error 

"Failed to copy Verthash data to the GPU memory"

**Comment by SveguS80** [comment]
**SOLVED!**

Thanks to @aim67  for his suggestion. It made me look more closely at the devices showing up in device manager at the time of running the time of generating the .dat file. I am administring this windows machine remotely and using Remote Desktop Connection, windows decides to add a virtual display adapter. That is counted as a CL device for some unknown reason and breaking the process after card number 4 for some reason. 

Thanks very much again.
