### ISSUE TITLE
Compiling on Ubuntu-20.04-LTS

### ISSUE THREAD

**Issue by JayDDee** [CryptoGraphics/VerthashMiner#31]
Compiling on Ubuntu-20.04-LTS fails due to a version check fail for cmake. However, it can compile and run on
Ubuntu-20.04 by reducing the minimum cmake version required. 

Edit CMakeLists.txt and change cmake_minimum_required from 3.18 to 3.16:
`cmake_minimum_required(VERSION 3.16)`

Cuda-10 requires gcc-8 or lower but Ubuntu installs gcc-9 by default. Install gcc-8 if not installed.
Configure cmake to use gcc-8:
`cmake .. -DCMAKE_C_COMPILER=gcc-8`

Then make as usual.

Older versions of cmake may also work but I have only tested with Ubuntu-20.04.
Please lower the cmake version requirement.

Edit: tested only with Cuda devices.

**Comment by CryptoGraphics** [comment]
Hello.
Those cmake version requirements were driven by issues discovered on the Windows platform.

**Comment by JayDDee** [comment]
Thanks for the reply. 

Perhaps the requirement can be made target specific. I would expect Windows users to use the binaries more and Linux
users to compile their own more often.

If you have no intention of making any changes feel free to close this.

**Comment by CryptoGraphics** [comment]
resolved in v0.7.1
