### ISSUE TITLE
Spelling mistake on Error 702

### ISSUE THREAD

**Issue by famousm1** [CryptoGraphics/VerthashMiner#34]
After getting error 702, the app says "Terminaning worker" and the word should be terminating

Thank you for this software!

**Comment by aimsml** [comment]
Hello. For 4-6-8 video cards, you need a lot of virtual memory , you need to increase the swap file, this will help!

**Comment by famousm1** [comment]
I'm not having any issues with the program; I was letting you know there is a spelling error when it throws that error #

**Comment by CryptoGraphics** [comment]
Resolved in v0.7.2.
