### ISSUE TITLE
ERROR cl_device(2):Failed start pipeline. error code: -63 in solo on VHM 0.7.0 and 0.7.1

### ISSUE THREAD

**Issue by aim67** [CryptoGraphics/VerthashMiner#36]
Hello. In verthashminer 0.7.1 , what is the cause of "ERROR cl_device(2):Failed start pipeline. error code: -63" e.t.c? Getting an error like that for all but one card, it'll hash with one but throws errors with the rest. VHM 0.6.2 works for all cards, no errors. VHM 0.7.0 and 0.7.1 do not work.

**Comment by CryptoGraphics** [comment]
Resolved in v0.7.2

**Comment by jimmyhollywood** [comment]
Have the similar issue on 0.72 but error code is 54. When I run mining it works around 10-15 minutes and then failed with 54 code
Works on old GPU amd r9 280, Ubuntu 14.04
