### ISSUE TITLE
VerthashDataFile does not accept non-ASCII characters | Windows

### ISSUE THREAD

**Issue by gaborwirth** [CryptoGraphics/VerthashMiner#4]
My windows username contains a non-ASCII character and it seems this prevent VerthashMiner to find the verthash.dat file.

For example my windows username is "Gábor", and the path to my verthash.dat is "C:/Users/Gábor/AppData/Roaming/Vertcoin/verthash.dat".

If I enter the path in verthash.conf  as VerthashDataFile = "C:/Users/Gábor/AppData/Roaming/Vertcoin/verthash.dat", I get the following error: ERROR Verthash data file name is invalid.
But if I modify the path to: VerthashDataFile = "C:/Users/Gbor~1/AppData/Roaming/Vertcoin/verthash.dat", the miner finds verthash.dat, and it works fine.

Unfortunately this operation makes the official OneClick Miner unusable, OCM recreates the verthash-miner.conf with VerthashDataFile="C:\Users\Gábor\AppData\Roaming\vertcoin-ocm\verthash.dat" at every restart, which cause the "ERROR Verthash data file name is invalid" error in VerthashMiner.

**Comment by CryptoGraphics** [comment]
Fixed in v0.6.2
