### ISSUE TITLE
Failed to create an OpenCL command queue. error code: -6

### ISSUE THREAD

**Issue by austinfrey** [CryptoGraphics/VerthashMiner#45]
I'm having trouble running the miner on some older cards: MSI R7950's (R9 208x)

When trying to run, i'm getting the following error: `Failed to create an OpenCL command queue. error code: -6`

I'm gathering that these older cards might not be suitable since more recent linux versions might not contain the amdgpu drivers that work for the Tahiti chips but not sure if that's correct.

OS: Ubuntu 18+ Bionic.

**Comment by jimmyhollywood** [comment]
I have the same.
OS: ubuntu 20.04
MSI R9 280 3Gb (amdgpu pro drivers)

Log:
`[2021-04-15 11:23:56] INFO  1 miner threads started, using Verthash algorithm.
[2021-04-15 11:23:56] DEBUG Verthash OCL thread started
[2021-04-15 11:23:56] ERROR cl_device(0):Failed to create an OpenCL command queue. error code: -6
[2021-04-15 11:23:56] INFO  cl_device(0):Exiting worker thread id(0)...
[2021-04-15 11:23:56] INFO  All worker threads have been exited.
[2021-04-15 11:23:56] DEBUG Exit workIO thread`

**Comment by jimmyhollywood** [comment]
@austinfrey looks like this is not a problem of miner.
You need to add some exports
export GPU_FORCE_64BIT_PTR=1
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100

Works for me perfectly. 
The original post https://community.amd.com/t5/drivers-software/solved-clinfo-reports-error-33-of-quot-global-free-memory-amd/td-p/172760
But I haven't checked the second part of solution
@CryptoGraphics  seems like you can just close this issue
