### ISSUE TITLE
Only 4 GB Ram used 

### ISSUE THREAD

**Issue by RafO123** [CryptoGraphics/VerthashMiner#5]
Hi,

I try to get better hashrates, but I think the main problem is, that the miner is not using the full potential of my graphic cards. It only uses 4 GB of memory and the workload is minimal at around 5 %. Is there a chance that I can use the full potential of my NVIDIA graphic cards?

Thanks a lot.

**Comment by KforG** [comment]
I think you are confused about how the verthash algorithm works. Verthash is I/O bound meaning it is not about how many Gb of memory is being used but rather the speed of the data being transferred, read more about it [here.](https://en.wikipedia.org/wiki/I/O_bound) This is also why overclocking your gpu's memory work. 

The task manager is very inaccurate in terms of how it measures workload unless you change around what workload you are monitoring. 

What gpu do you have?

**Comment by CryptoGraphics** [comment]
Verthash algorithm is not that "heavy" in terms of memory space requirements.
Miner uses ~1.2GB for the verthash data + (36 bytes * Work_Batch_Size).
