### ISSUE TITLE
Help wanted please about data buffer size

### ISSUE THREAD

**Issue by Saikatsaha1996** [CryptoGraphics/VerthashMiner#52]
Any solution please?
OpenCL 2.0 available
![Screenshot_2021-07-06-01-05-48-612_com termux](https://user-images.githubusercontent.com/72664192/124512652-83ed6a80-ddf6-11eb-80bf-b4b5ec1faf00.jpg)
![Screenshot_2021-07-06-01-08-17-845_com termux](https://user-images.githubusercontent.com/72664192/124512718-abdcce00-ddf6-11eb-965e-d43186eb2001.jpg)

**Comment by Saikatsaha1996** [comment]
My config 
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

<Connection Algorithm = "Verthash"                                                                                                                                  Url = "stratum+tcp://verthash.eu.mine.zergpool.com:4534"
            Username = "MDiEYbtkYWequn9ByFFAeQ3HHZp1ARXsqi"
            Password = "c=LTC"
            CoinbaseAddress = ""
            CoinbaseSignature = ""
            SSLCertificateFileName = ""
            Proxy = ""
            Redirect = "true"
            LongPoll = "true"
            LongPollTimeout = "0"
            Scantime = "5"
            Retries = "-1"
            RetryPause = "30"
            ProtocolDump = "false">

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# OpenCL device config:
#
# Available platforms:
#
# 1. Platform name: QUALCOMM
#    Index: 0
#
# Available devices:
#
# DeviceIndex: 0
#    Name: QUALCOMM Adreno(TM)
#    PCIeId: not avilable
#    Platform index: 0
#
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

<CL_Device0 DeviceIndex = "0" BinaryFormat = "auto" AsmProgram = "none" WorkSize = "0" BatchTimeMs = "500" OccupancyPct = "100" DeviceMonitor = "1" GPU>

**Comment by Saikatsaha1996** [comment]
It's possible to reduce data size?..
![Screenshot_2021-07-06-01-20-41-827_com termux](https://user-images.githubusercontent.com/72664192/124513448-776a1180-ddf8-11eb-918d-8ff948b74992.jpg)

**Comment by Saikatsaha1996** [comment]
No solution available?

**Comment by Saikatsaha1996** [comment]
> Any solution please? OpenCL 2.0 available ![Screenshot_2021-07-06-01-05-48-612_com termux](https://user-images.githubusercontent.com/72664192/124512652-83ed6a80-ddf6-11eb-80bf-b4b5ec1faf00.jpg) ![Screenshot_2021-07-06-01-08-17-845_com termux](https://user-images.githubusercontent.com/72664192/124512718-abdcce00-ddf6-11eb-965e-d43186eb2001.jpg)

@CryptoGraphics  how to reduce VTC data buffer size ?.. mey be need to some modifications for work.. can you tell me please.. 

Total OpenCL global memory 3.5 GB
maximum allocated memory 900MB

Which codes need to be edite ?
Can you please help ?

**Comment by Saikatsaha1996** [comment]
@CryptoGraphics mey be i should change value in this file.. but actually i don't know anything about coding if you help me it's really very much helpful for me thank you

https://github.com/CryptoGraphics/VerthashMiner/blob/main/src/vhCore/Verthash.cpp

**Comment by sylvesternumski** [comment]
Are you setting the following environment vars prior to launching?
export GPU_FORCE_64BIT_PTR=1
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100

**Comment by Saikatsaha1996** [comment]
> @CryptoGraphics mey be i should change value in this file.. but actually i don't know anything about coding if you help me it's really very much helpful for me thank you



> Are you setting the following environment vars prior to launching? export GPU_FORCE_64BIT_PTR=1 export GPU_USE_SYNC_OBJECTS=1 export GPU_MAX_ALLOC_PERCENT=100 export GPU_SINGLE_ALLOC_PERCENT=100 export GPU_MAX_HEAP_SIZE=100

Already tried...@sylvesternumski


```
#!/bin/sh
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_USE_SYNC_OBJECTS=1
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_ALLOC_PERCENT=100
export GPU_MAX_SINGLE_ALLOC_PERCENT=100
export GPU_ENABLE_LARGE_ALLOCATION=100
export GPU_MAX_WORKGROUP_SIZE=1024
```
But not working because memory available only 900MB for max allocation
Total 3.9GB memory

![IMG_20220527_174733](https://user-images.githubusercontent.com/72664192/170697872-d95a2fbf-5a9b-4d88-8efd-9fe70a4ff776.jpg)

**Comment by Saikatsaha1996** [comment]
@sylvesternumski can you teach me about how can I change VTC data buffer size by code ?
Mey be need to change in this .cpp file for data buffer size.. 
https://github.com/CryptoGraphics/VerthashMiner/blob/main/src/vhCore/Verthash.cpp

**Comment by sylvesternumski** [comment]
The data buffer might be limited by hardware.  What card are you trying to run this on?  In order to support the verthash algorithm, you need at least 2GB dedicated ram on the card itself.

**Comment by Saikatsaha1996** [comment]
@sylvesternumski 
Actually it is android device with full OpenCL 2.0 support, gcn 1.0 comfortable
Actually only memory requirment not matching.. 


That's why I am asking for help.. just wanted to reduce memory size ..

It is experimental .. so if i am getting help i would be very helpful for me..

**Comment by sylvesternumski** [comment]
Memory requirements are the most import part, the size of the verthash dat file cannot be modified, this is one part of the algorithm that makes it ASIC resistant.  You might be able to modify the code to use a file instead but then your hashrate would be severely diminished.

**Comment by Saikatsaha1996** [comment]
@sylvesternumski 
I don't need performance.. i don't need anything.. i am doing it only for experimental purpose only.. 

Can you help me for reduce `verthash dat` file ?..
I just want to use..

**Comment by sylvesternumski** [comment]
You cannot reduce the verthash dat file size.  If you really want it to be usable on other platforms, you can attempt to convert the miner to use a file instead of ram, the p2pool and other pools do this for confirming share submissions.  I haven't really looked into the code beyond building it as is.

**Comment by Saikatsaha1996** [comment]
> You cannot reduce the verthash dat file size. If you really want it to be usable on other platforms, you can attempt to convert the miner to use a file instead of ram, the p2pool and other pools do this for confirming share submissions. I haven't really looked into the code beyond building it as is.

@sylvesternumski How can I do this for verthash dat useing ram ?

**Comment by Saikatsaha1996** [comment]
> You cannot reduce the verthash dat file size. If you really want it to be usable on other platforms, you can attempt to convert the miner to use a file instead of ram, the p2pool and other pools do this for confirming share submissions. I haven't really looked into the code beyond building it as is.

Can you tell me how to do?

**Comment by Saikatsaha1996** [comment]
> You cannot reduce the verthash dat file size. If you really want it to be usable on other platforms, you can attempt to convert the miner to use a file instead of ram, the p2pool and other pools do this for confirming share submissions. I haven't really looked into the code beyond building it as is.

Memory requirment solved but new error..
Help!

```
[2022-12-13 08:15:45] INFO  Found 1 OpenCL devices.
[2022-12-13 08:15:45] INFO  Using a configuration file (miner.conf)
[2022-12-13 08:15:45] INFO  Loading verthash data file...
[2022-12-13 08:15:46] INFO  Verthash data file has been loaded succesfully!
[2022-12-13 08:15:46] INFO  Verifying verthash data file...
[2022-12-13 08:15:50] INFO  Verthash data file has been verified succesfully!
[2022-12-13 08:15:50] INFO  Using protocol: Stratum.
[2022-12-13 08:15:50] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 0)
[2022-12-13 08:15:50] INFO  Configured 1(CL) workers
[2022-12-13 08:15:50] INFO  1 miner threads started, using Verthash algorithm.
[2022-12-13 08:15:50] WARN  cl_device(0):Monitoring has been disabled. No backends available!
[2022-12-13 08:15:50] INFO  Starting Stratum on stratum+tcp://verthash.asia.mine.zergpool.com:4534
[2022-12-13 08:15:51] INFO  Stratum difficulty set to 2
[2022-12-13 08:15:51] INFO  Verthash block: 1892428
Failed to read file: kernels/sha3_512_precompute.cl
Failed to create an OpenCL program from source.
[2022-12-13 08:15:52] ERROR cl_device(0):Failed to create a SHA3 precompute program.
[2022-12-13 08:15:52] INFO  cl_device(0):Exiting worker thread id(0)...
[2022-12-13 08:15:52] INFO  All worker threads have been exited.
[2022-12-13 08:15:52] INFO  WorkIO thread has been finished.
[2022-12-13 08:15:52] INFO  Waiting for worker threads to exit...
[2022-12-13 08:15:52] INFO  Waiting for stratum thread to exit...
[2022-12-13 08:15:52] ERROR Stratum connection interrupted
[2022-12-13 08:15:52] DEBUG Stratum thread exit
[2022-12-13 08:15:52] INFO  Freeing allocated memory...
[2022-12-13 08:15:52] INFO  Application has been exited gracefully.
~/VerthashMiner/build $
```

**Comment by sylvesternumski** [comment]
kernels/sha3_512_precompute.cl is part of a directory in the distribution that needs to be in the directory you're running the miner. It's the opencl routines that are run on the card to perform the mining.

**Comment by Saikatsaha1996** [comment]
> kernels/sha3_512_precompute.cl is part of a directory in the distribution that needs to be in the directory you're running the miner. It's the opencl routines that are run on the card to perform the mining.

Android GPU mining 😂🤣
But thank you so much for your fast to last time help

![IMG_20221213_085124](https://user-images.githubusercontent.com/72664192/207218716-d2a18d92-af7d-4923-9ab9-92fafeadc173.jpg)

**Comment by sylvesternumski** [comment]
That's just slightly faster than I can hash by hand.  Nice, put it into a wallet and have it hash in the background. Might be interesting but my guess is it'll eat the battery. (Maybe only hash when plugged in?)

**Comment by Saikatsaha1996** [comment]
> That's just slightly faster than I can hash by hand. Nice, put it into a wallet and have it hash in the background. Might be interesting but my guess is it'll eat the battery. (Maybe only hash when plugged in?)

Battery temp 38°C
Total watt 1.3 Watts

**Comment by sylvesternumski** [comment]
Back of the napkin calc tells me that ain't too bad for khash/watt.  Is the 1.3 just the gpu?

**Comment by Saikatsaha1996** [comment]
> Back of the napkin calc tells me that ain't too bad for khash/watt. Is the 1.3 just the gpu?

Sir i know.. actually i am not professional miner..
And it is not for profit.. just for fun only..
My pc given me 450 kh/s with 55watts only..
I just like test with android GPU capabilities..
I am not mining now.. just testing with android GPU..
🙈

**Comment by Saikatsaha1996** [comment]
> Back of the napkin calc tells me that ain't too bad for khash/watt. Is the 1.3 just the gpu?

`12 hrs` reward results with `8.85 kh/s`
Max temperature `35 to 39°C` after `12 hrs`


![IMG_20221214_194149](https://user-images.githubusercontent.com/72664192/207617896-de10d3a4-0d6e-4697-bea2-462c7ad80eb5.jpg)
![Screenshot_2022-12-14-14-01-55-469_com termux](https://user-images.githubusercontent.com/72664192/207618758-6ea8aa51-1b09-4a5d-990d-37385acd787a.jpg)
