### ISSUE TITLE
it does not work more then 8 gpu

### ISSUE THREAD

**Issue by alptolga** [CryptoGraphics/VerthashMiner#62]
Hi I have 13 gpus in my rig but it only works with 8 gpus.

**Comment by sylvesternumski** [comment]
What OS?

**Comment by alptolga** [comment]
windows 10
13 gpu worked. The problem was caused by my stupidity. The 2nd psu was turned off and 8 gpu was already active in the system. After the 2nd psu was turned on, 13 gpu worked.
